modified mbp-parse-all to check that data files exist before attempting to generate reports

diff --git a/mbp-parse-all b/mbp-parse-all
--- a/mbp-parse-all
+++ b/mbp-parse-all
@@ -31,23 +31,21 @@ $(basename $0) will create filenames in the YYYY-MM-DD_HH-<dataParentDir>-<repor
     esac
 done
 
-# set report filenames to YYYY-MM-DD_HH-<INPUTDIR_parent>-<report_name>
-NAMEROOT=$(basename $INPUTDIR)
-QPS=$(find $INPUTDIR $MAXDEPTH -type f -name "*-status" | \
-    sort -d | grep -m 1 -E -o '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}')-$NAMEROOT-QPS
-DISKSTATS=$(find $INPUTDIR $MAXDEPTH -type f -name "*-diskstats" | \
-    sort -d | grep -m 1 -E -o '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}')-$NAMEROOT-diskstats
-LSOF=$(find $INPUTDIR $MAXDEPTH -type f -name "*-lsof" | \
-    sort -d | grep -m 1 -E -o '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}')-$NAMEROOT-lsof
-QUERYPROFILE=$(find $INPUTDIR $MAXDEPTH -type f -name "*-tcpdump" | \
-    sort -d | grep -m 1 -E -o '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}')-$NAMEROOT-queryprofile
+# set report filename root to YYYY-MM-DD_HH-<INPUTDIR_parent> of first status file
+STATUSFILE=$(find $INPUTDIR $MAXDEPTH -type f -name "*-status" | \
+    sort -d | grep -m 1 -E -o '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}')
+if [ -z "$STATUSFILE" ]; then
+    echo "error - could not find status data file(s) in $INPUTDIR"; 
+    exit 1;
+fi
+NAMEROOT=$STATUSFILE-$(basename $INPUTDIR)
 
 # generate reports
-echo "Generating $QPS"
-$SCRIPTDIR/mbp-parse-status $INPUTDIR/*-status > $OUTPUTDIR/$QPS
-echo "Generating $DISKSTATS for sda"
-pt-diskstats $INPUTDIR/*-diskstats | grep -E 'sda\s' > $OUTPUTDIR/$DISKSTATS
-echo "Generating $LSOF"
-$SCRIPTDIR/mbp-parse-lsof $INPUTDIR/*-lsof > $OUTPUTDIR/$LSOF
-echo "Generating $QUERYPROFILE"
-pt-query-digest --type tcpdump $INPUTDIR/*-tcpdump > $OUTPUTDIR/$QUERYPROFILE
+echo "Generating $NAMEROOT-QPS"
+$SCRIPTDIR/mbp-parse-status $INPUTDIR/*-status > $OUTPUTDIR/$NAMEROOT-QPS
+echo "Generating $NAMEROOT-diskstats for sda"
+pt-diskstats $INPUTDIR/*-diskstats | grep -E 'sda\s' > $OUTPUTDIR/$NAMEROOT-diskstats
+echo "Generating $NAMEROOT-lsof"
+$SCRIPTDIR/mbp-parse-lsof $INPUTDIR/*-lsof > $OUTPUTDIR/$NAMEROOT-lsof
+echo "Generating $NAMEROOT-queryprofile"
+pt-query-digest --type tcpdump $INPUTDIR/*-tcpdump > $OUTPUTDIR/$NAMEROOT-queryprofile
